# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: "Killian O'Brien"
title: Technical Implementation Manager
email: killian@killianobrien.dev
# email_title: Email (Email title override)
phone: (423) 314-2104
# phone_title: Phone (Phone title override)
website: linkedin.com/in/KillianOBrien
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  KillianGOBrien
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: KillianOBrien
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: "/images/profile.jpg"
about_content: | # this will include new lines to allow paragraphs
  I’m Killian O'Brien, a results-driven Technical Implementation Manager with a passion for software systems maintenance, customization, and optimization. At Gateway Electronic Medical Management Systems, I ensure that our software solutions not only meet but exceed client expectations by integrating process improvements and custom features that enhance functionality.
  With a background in .NET Core, Object-Oriented Programming (OOP), and database management, I work closely with DBAs and engineers to streamline support tools and improve system performance. My ability to communicate fluently in English and Spanish enables me to engage with a diverse client base, ensuring seamless project execution.
  Beyond my current role, my experience spans software development, general contracting, underground utility locating, and sales, giving me a well-rounded perspective on problem-solving and project management. I take pride in my adaptability and commitment to delivering high-quality technical solutions.
  
  Let’s connect and discuss how I can bring value to your team or project!

content:
  #- title: Projects # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: left
  #      border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
  #      title: Project name
  #      link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #      link_text: Link Text
  #      additional_links:
  #        - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #          icon: fab fa-github
  #          url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #        - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #          icon: fab fa-github
  #          url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #      quote: >
  #        Short overview of the project (optional)
  #      description: | # this will include new lines to allow paragraphs
  #        Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: right
        title: GEMMS
        sub_title: Technical Implementation Manager
        caption: January 2021 - Present
        link: https://gemmsone.com/
        quote: >
        description: | # this will include new lines to allow paragraphs
          Ensure that software systems are properly maintained, fully functional, and optimized to meet client needs. I install, configure, and customize software solutions, tailoring them to align with specific operational requirements. Working closely with DBAs and engineering teams, I contribute to feature enhancements, troubleshoot issues, and develop tools to streamline support processes. Additionally, I serve as the primary knowledge holder for multiple product lines, providing critical expertise to support teams, guide implementations, and drive continuous improvements in system performance and functionality.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Indiana University - Purdue University - Indianapolis
        sub_title: BA Science
        description: | # this will include new lines to allow paragraphs
          Computer Science
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I’m a dedicated father of two, balancing homeschooling during the day with my professional career in the evenings. Alongside my work, I’m currently pursuing the IBM DevOps and Software Engineering Professional Certificate, continuously expanding my technical expertise.

      My background as a gymnast from age five through college instilled in me a strong foundation in time management, discipline, and prioritization—skills that seamlessly translate into both my personal and professional life. Juggling multiple responsibilities has sharpened my ability to stay focused, adapt quickly, and tackle challenges head-on.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
